name: Make Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the new release
        required: true
        type: string
        default: 0.1.0

jobs:
  make-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          target/
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.toml') }}

    - uses: dtolnay/rust-toolchain@stable

    - name: Update CHANGELOG.md version
      run: |
        release_date=$(date --utc +%Y-%m-%d)
        version='v${{ inputs.version }}'
        sed -zi \
          "s/# Changelog\n\n## Unreleased - XXXX-XX-XX/# Changelog\n\n## Unreleased - XXXX-XX-XX\n\n## $version - $release_date/" \
          CHANGELOG.md

    - name: Update Cargo.toml version
      run: |
        # Change the first match, which should be ours.
        sed -i '0,/version = ".*"/s//version = "${{ inputs.version }}"/' Cargo.toml

    - name: Update Cargo
      run: |
        cargo update

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        branch: release-v${{ inputs.version }}
        commit-message: |
          Release v${{ inputs.version }}

          Update version in CHANGELOG.md
          Update version in Cargo.toml
          Update Cargo.lock
        title: Release v${{ inputs.version }}
        body: |
          Make release for v${{ inputs.version }} by workflow
