name: Make Bevy Migration PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: The new Bevy version
        required: true
        type: string
        default: 0.1.0

jobs:
  make-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - uses: dtolnay/rust-toolchain@stable

    # Notes with sed:
    # We uses -z in order to treat the entire file as a single input needed to match newlines.
    # & Means to use the matched regex within the substituion.
    # t and q1 is used to exit with code 1 to indicate that the substitution fails.

    - name: Update CHANGELOG.md version
      run: |
        release_date=$(date --utc +%Y-%m-%d)
        version='v${{ inputs.version }}'
        sed -zi \
          "s/# Changelog\n\n## Unreleased - XXXX-XX-XX\n/&\n## $version - $release_date\n/; t; q1" \
          CHANGELOG.md

    - name: Update Cargo
      run: |
        cargo update

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        branch: release-v${{ inputs.version }}
        commit-message: Release v${{ inputs.version }}
        title: Release v${{ inputs.version }}
        body: Make release for v${{ inputs.version }} by workflow

