name: Make Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the new release
        required: true
        type: string
        default: 0.1.0
      bevy_version:
        description: Bevy version this release uses
        required: true
        type: string
        default: 0.1.0

jobs:
  make-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
      with:
        token: ${{ secrets.TOKEN }}

    - uses: dtolnay/rust-toolchain@stable

    - name: Setup Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git branch -c 'release-v${{ inputs.version }}'

    # Notes with sed:
    # We uses -z in order to treat the entire file as a single input needed to match newlines.
    # & Means to use the matched regex within the substituion.
    # t and q1 is used to exit with code 1 when the substitution fails.

    - name: Update CHANGELOG.md version
      run: |
        release_date=$(date --utc +%Y-%m-%d)
        version='v${{ inputs.version }}'
        sed -zi \
          "s/# Changelog\n\n## Unreleased - XXXX-XX-XX\n/&\n## $version - $release_date\n/; t; q1" \
          CHANGELOG.md
        git add CHANGELOG.md
        git commit -m 'Update CHANGELOG.md latest version'

    - name: Update README.md bevy version support table
      run: |
        row=$(printf "| %-6s | %-12s |" '${{ inputs.bevy_version }}' '${{ inputs.version }}' )
        sed -zi \
          "s/## Bevy Version Support\n\n| \`bevy\` | \`bevy_tween\` |\n|--------|--------------|\n/&$row\n/; t; q1" \
          README.md
        git add README.md
        git commit -m 'Update Bevy version support in README.md'

    - name: Update Cargo.toml version
      run: |
        # Only replace the first match, which should be ours.
        sed -zi \
          's/version = "[^"]*"/version = "${{ inputs.version }}"/; t; q1' \
          Cargo.toml
        git commit -m 'Update Cargo.toml version'

    - name: Update Cargo
      run: |
        cargo update

    - name: Create Pull Request
      # uses: peter-evans/create-pull-request@v8
      # with:
      #   token: ${{ secrets.RELEASE_TOKEN }}
      #   branch: release-v${{ inputs.version }}
      #   commit-message: Release v${{ inputs.version }}
      #   title: Release v${{ inputs.version }}
      #   body: Make release for v${{ inputs.version }} by workflow
      env:
        GH_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git push origin release-v${{ inputs.version }}

        pr_url=$(
          gh pr create \
            --title "Release v${{ inputs.version }}"
            --body "\
              # Objective\n\
              - Make release for v${{ inputs.version }}\n\
              \n\
              This PR was automatically generated by a GitHub Actions workflow.\n\
            "
        )
        echo $pr_url
