name: Make Bevy Migration PR

on:
  workflow_dispatch:
    inputs:
      bevy_version:
        description: The new Bevy version
        required: true
        type: string
        default: 0.1.0

jobs:
  make-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
      with:
        token: ${{ secrets.TOKEN }}

    - uses: dtolnay/rust-toolchain@stable

    - name: Setup Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git switch -c 'bevy-v${{ inputs.bevy_version }}'

    - name: Install toml-cli
      run: |
        cargo install toml-cli
    #   run: |
    #     curl -OL https://github.com/gnprice/toml-cli/releases/download/v0.2.3/toml-0.2.3-x86_64-linux.tar.gz
    #     tar -xf toml-0.2.3-x86_64-linux.tar.gz
    #     mv toml-0.2.3-x86_64-linux/toml .

    - name: Update Bevy dependencies
      env:
        QUERIES: ${{ vars.BEVY_QUERY_AUTO_UPDATE }}
      run: |
        for query in $QUERIES; do
          # Buffer the output first before redirecting otherwise the content will be very wrong
          echo "$(toml set Cargo.toml $query '${{ inputs.bevy_version }}')" > Cargo.toml
        done
        git add Cargo.toml
        git commit -m "Update Bevy dependencies"

    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ secrets.TOKEN }}
        BODY: |
          # Objective
          Migrate to Bevy v${{ inputs.bevy_version }}
        
          This PR was automatically generated by a GitHub Actions workflow.
      run: |
        git push -u origin bevy-v${{ inputs.bevy_version }}

        pr_url=$(
          gh pr create \
            --title "Migrate to Bevy v${{ inputs.bevy_version }}" \
            --body "$BODY"
        )
        echo "PR_URL=$pr_url" >> $GITHUB_ENV

    - name: Add PR to CHANGELOG.md
      run: |
        pr_num="${PR_URL##*/}"
        content="- Migrate to Bevy v${{ inputs.bevy_version }} by [#$pr_num]($PR_URL)"
        escaped_content=$(printf '%s\n' "$content" | sed -e 's/[\/&]/\\&/g')
        sed -zi \
          "s/# Changelog\n\n## Unreleased - XXXX-XX-XX\n/&$escaped_content\n/; t; q1" \
          CHANGELOG.md

        git add CHANGELOG.md
        git commit -m "Update CHANGELOG.md"
        git push
